# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/ruby/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/ruby/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/htc/ruby/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/ruby/proprietary/libacdbloader.so:obj/lib/libacdbloader.so \
    vendor/htc/ruby/proprietary/libacdbmapper.so:obj/lib/libacdbmapper.so \
    vendor/htc/ruby/proprietary/lib/libril.so:obj/lib/libril.so

# All the blobs necessary for ruby
PRODUCT_COPY_FILES += \
    vendor/htc/ruby/proprietary/bin/akmd:/system/bin/akmd \
    vendor/htc/ruby/proprietary/bin/awb_camera:/system/bin/awb_camera \
    vendor/htc/ruby/proprietary/bin/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/ruby/proprietary/bin/charging:/system/bin/charging \
    vendor/htc/ruby/proprietary/bin/dcvs:/system/bin/dcvs \
    vendor/htc/ruby/proprietary/bin/dcvsd:/system/bin/dcvsd \
    vendor/htc/ruby/proprietary/bin/hdmid:/system/bin/hdmid \
    vendor/htc/ruby/proprietary/bin/htcbatt:/system/bin/htcbatt \
    vendor/htc/ruby/proprietary/bin/ip:/system/bin/ip \
    vendor/htc/ruby/proprietary/bin/ipd:/system/bin/ipd \
    vendor/htc/ruby/proprietary/bin/ks:/system/bin/ks \
    vendor/htc/ruby/proprietary/bin/load-modem.sh:/system/bin/load-modem.sh \
    vendor/htc/ruby/proprietary/bin/logcat2:/system/bin/logcat2 \
    vendor/htc/ruby/proprietary/bin/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/ruby/proprietary/bin/mpdecision:/system/bin/mpdecision \
    vendor/htc/ruby/proprietary/bin/qcks:/system/bin/qcks \
    vendor/htc/ruby/proprietary/bin/qmuxd:/system/bin/qmuxd \
    vendor/htc/ruby/proprietary/bin/rild:/system/bin/rild \
    vendor/htc/ruby/proprietary/bin/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/ruby/proprietary/bin/sdcard:/system/bin/sdcard \
    vendor/htc/ruby/proprietary/bin/ser2net:/system/bin/ser2net \
    vendor/htc/ruby/proprietary/bin/sh:/system/bin/sh \
    vendor/htc/ruby/proprietary/bin/sh0:/system/bin/sh0 \
    vendor/htc/ruby/proprietary/bin/sound8x60:/system/bin/sound8x60 \
    vendor/htc/ruby/proprietary/bin/thermald:/system/bin/thermald \
    vendor/htc/ruby/proprietary/bin/tiap_loader:/system/bin/tiap_loader \
    vendor/htc/ruby/proprietary/bin/tiwlan_loader:/system/bin/tiwlan_loader \
    vendor/htc/ruby/proprietary/bin/vold:/system/bin/vold \
    vendor/htc/ruby/proprietary/bin/wlan_cu:/system/bin/wlan_cu \
    vendor/htc/ruby/proprietary/bin/wpa_cli:/system/bin/wpa_cli \
    vendor/htc/ruby/proprietary/bin/wpa_supplicant:/system/bin/wpa_supplicant \
    vendor/htc/ruby/proprietary/etc/wifi/firmware.bin:/system/etc/wifi/firmware.bin \
    vendor/htc/ruby/proprietary/etc/wifi/firmware_ap.bin:/system/etc/wifi/firmware_ap.bin \
    vendor/htc/ruby/proprietary/etc/wifi/hostapd.conf:/system/etc/wifi/hostapd.conf \
    vendor/htc/ruby/proprietary/etc/wifi/tiwlan.ini:/system/etc/wifi/tiwlan.ini \
    vendor/htc/ruby/proprietary/etc/wifi/tiwlan_ap.ini:/system/etc/wifi/tiwlan_ap.ini \
    vendor/htc/ruby/proprietary/etc/agps_rm:/system/etc/agps_rm \
    vendor/htc/ruby/proprietary/etc/spn-conf.xml:/system/etc/spn-conf.xml \
    vendor/htc/ruby/proprietary/etc/st_drv.ko:/system/etc/st_drv.ko \
    vendor/htc/ruby/proprietary/etc/thermald.conf:/system/etc/thermald.conf \
    vendor/htc/ruby/proprietary/etc/ti_hci_drv.ko:/system/etc/ti_hci_drv.ko \
    vendor/htc/ruby/proprietary/etc/voicemail-conf.xml:/system/etc/voicemail-conf.xml \
    vendor/htc/ruby/proprietary/etc/vpimg:/system/etc/vpimg \
    vendor/htc/ruby/proprietary/lib/egl/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/ruby/proprietary/lib/egl/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/ruby/proprietary/lib/egl/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/ruby/proprietary/lib/egl/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/ruby/proprietary/lib/hw/copybit.msm8660.so:/system/lib/hw/copybit.msm8660.so \
    vendor/htc/ruby/proprietary/lib/hw/gps.ruby.so:/system/lib/hw/gps.ruby.so \
    vendor/htc/ruby/proprietary/lib/hw/gralloc.default.so:/system/lib/hw/gralloc.default.so \
    vendor/htc/ruby/proprietary/lib/hw/gralloc.msm8660.so:/system/lib/hw/gralloc.msm8660.so \
    vendor/htc/ruby/proprietary/lib/hw/lights.msm8660.so:/system/lib/hw/lights.msm8660.so \
    vendor/htc/ruby/proprietary/lib/hw/overlay.default.so:/system/lib/hw/overlay.default.so \
    vendor/htc/ruby/proprietary/lib/hw/sensors.ruby.so:/system/lib/hw/sensors.ruby.so \
    vendor/htc/ruby/proprietary/lib/libaudio.so:/system/lib/libaudio.so \
    vendor/htc/ruby/proprietary/lib/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/ruby/proprietary/lib/libauth.so:/system/lib/libauth.so \
    vendor/htc/ruby/proprietary/lib/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/ruby/proprietary/lib/libdiag.so:/system/lib/libdiag.so \
    vendor/htc/ruby/proprietary/lib/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
    vendor/htc/ruby/proprietary/lib/libdsm.so:/system/lib/libdsm.so \
    vendor/htc/ruby/proprietary/lib/libdsnet.so:/system/lib/libdsnet.so \
    vendor/htc/ruby/proprietary/lib/libdsprofile.so:/system/lib/libdsprofile.so \
    vendor/htc/ruby/proprietary/lib/libdss.so:/system/lib/libdss.so \
    vendor/htc/ruby/proprietary/lib/libdssock.so:/system/lib/libdssock.so \
    vendor/htc/ruby/proprietary/lib/libdsutils.so:/system/lib/libdsutils.so \
    vendor/htc/ruby/proprietary/lib/libewtzmu2cali.so:/system/lib/libewtzmu2cali.so \
    vendor/htc/ruby/proprietary/lib/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/ruby/proprietary/lib/libgsdi_exp.so:/system/lib/libgsdi_exp.so \
    vendor/htc/ruby/proprietary/lib/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/ruby/proprietary/lib/libgstk_exp.so:/system/lib/libgstk_exp.so \
    vendor/htc/ruby/proprietary/lib/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/ruby/proprietary/lib/libidl.so:/system/lib/libidl.so \
    vendor/htc/ruby/proprietary/lib/libloc_api-rpc-qc.so:/system/lib/libloc_api-rpc-qc.so \
    vendor/htc/ruby/proprietary/lib/libmllite.so:/system/lib/libmllite.so \
    vendor/htc/ruby/proprietary/lib/libmlplatform.so:/system/lib/libmlplatform.so \
    vendor/htc/ruby/proprietary/lib/libmmgsdilib.so:/system/lib/libmmgsdilib.so \
    vendor/htc/ruby/proprietary/lib/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/ruby/proprietary/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/ruby/proprietary/lib/libmpl.so:/system/lib/libmpl.so \
    vendor/htc/ruby/proprietary/lib/libmpl_jni.so:/system/lib/libmpl_jni.so \
    vendor/htc/ruby/proprietary/lib/libnetmgr.so:/system/lib/libnetmgr.so \
    vendor/htc/ruby/proprietary/lib/libnv.so:/system/lib/libnv.so \
    vendor/htc/ruby/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/ruby/proprietary/lib/liboem_rapi.so:/system/lib/liboem_rapi.so \
    vendor/htc/ruby/proprietary/lib/liboem_rapi_fusion.so:/system/lib/liboem_rapi_fusion.so \
    vendor/htc/ruby/proprietary/lib/libOmxCore.so:/system/lib/libOmxCore.so \
    vendor/htc/ruby/proprietary/lib/libOmxVdec.so:/system/lib/libOmxVdec.so \
    vendor/htc/ruby/proprietary/lib/libOmxVenc.so:/system/lib/libOmxVenc.so \
    vendor/htc/ruby/proprietary/lib/liboncrpc.so:/system/lib/liboncrpc.so \
    vendor/htc/ruby/proprietary/lib/liboverlay.so:/system/lib/liboverlay.so \
    vendor/htc/ruby/proprietary/lib/libpbmlib.so:/system/lib/libpbmlib.so \
    vendor/htc/ruby/proprietary/lib/libpbmlib_fusion.so:/system/lib/libpbmlib_fusion.so \
    vendor/htc/ruby/proprietary/lib/libpdapi.so:/system/lib/libpdapi.so \
    vendor/htc/ruby/proprietary/lib/libpdsm_atl.so:/system/lib/libpdsm_atl.so \
    vendor/htc/ruby/proprietary/lib/libping_lte_rpc.so:/system/lib/libping_lte_rpc.so \
    vendor/htc/ruby/proprietary/lib/libping_mdm.so:/system/lib/libping_mdm.so \
    vendor/htc/ruby/proprietary/lib/libqcommon.so:/system/lib/libqcommon.so \
    vendor/htc/ruby/proprietary/lib/libqdp.so:/system/lib/libqdp.so \
    vendor/htc/ruby/proprietary/lib/libqdsp.so:/system/lib/libqdsp.so \
    vendor/htc/ruby/proprietary/lib/libqmi.so:/system/lib/libqmi.so \
    vendor/htc/ruby/proprietary/lib/libqmiservices.so:/system/lib/libqmiservices.so \
    vendor/htc/ruby/proprietary/lib/libqueue.so:/system/lib/libqueue.so \
    vendor/htc/ruby/proprietary/lib/libreference-ril.so:/system/lib/libreference-ril.so \
    vendor/htc/ruby/proprietary/lib/libril.so:/system/lib/libril.so \
    vendor/htc/ruby/proprietary/lib/libril-qc-qmi-1.so:/system/lib/libril-qc-qmi-1.so \
    vendor/htc/ruby/proprietary/lib/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so \
    vendor/htc/ruby/proprietary/lib/libril_status.so:/system/lib/libril_status.so \
    vendor/htc/ruby/proprietary/xbin/wireless_modem:/system/xbin/wireless_modem \
