# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/evita/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/htc/evita/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
	vendor/htc/evita/proprietary/lib/libril.so:obj/lib/libril.so \
	vendor/htc/evita/proprietary/lib/libv8.so:obj/lib/libv8.so

PRODUCT_COPY_FILES += \
  vendor/htc/evita/proprietary/etc/agps_rm:system/etc/agps_rm \
  vendor/htc/evita/proprietary/bin/akmd:system/bin/akmd \
  vendor/htc/evita/proprietary/bin/charging:system/bin/charging \
  vendor/htc/evita/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
  vendor/htc/evita/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
  vendor/htc/evita/proprietary/bin/mpdecision:system/bin/mpdecision \
  vendor/htc/evita/proprietary/bin/netmgrd:system/bin/netmgrd \
  vendor/htc/evita/proprietary/bin/netsharing:system/bin/netsharing \
  vendor/htc/evita/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/htc/evita/proprietary/bin/qmuxd:system/bin/qmuxd \
  vendor/htc/evita/proprietary/bin/thermald:system/bin/thermald \
  vendor/htc/evita/proprietary/bin/time_daemon:system/bin/time_daemon \
  vendor/htc/evita/proprietary/bin/zchgd:system/bin/zchgd \
  vendor/htc/evita/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
  vendor/htc/evita/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
  vendor/htc/evita/proprietary/lib/libchromatix_s5k3h2yx_default_video.so:system/lib/libchromatix_s5k3h2yx_default_video.so \
  vendor/htc/evita/proprietary/lib/libchromatix_s5k3h2yx_hdr.so:system/lib/libchromatix_s5k3h2yx_hdr.so \
  vendor/htc/evita/proprietary/lib/libchromatix_s5k3h2yx_hfr.so:system/lib/libchromatix_s5k3h2yx_hfr.so \
  vendor/htc/evita/proprietary/lib/libchromatix_s5k3h2yx_preview.so:system/lib/libchromatix_s5k3h2yx_preview.so \
  vendor/htc/evita/proprietary/lib/libchromatix_s5k3h2yx_zsl.so:system/lib/libchromatix_s5k3h2yx_zsl.so \
  vendor/htc/evita/proprietary/lib/libchromatix_s5k6a1gx_default_video.so:system/lib/libchromatix_s5k6a1gx_default_video.so \
  vendor/htc/evita/proprietary/lib/libchromatix_s5k6a1gx_preview.so:system/lib/libchromatix_s5k6a1gx_preview.so \
  vendor/htc/evita/proprietary/lib/libchromatix_s5k6a1gx_zsl.so:system/lib/libchromatix_s5k6a1gx_zsl.so \
  vendor/htc/evita/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
  vendor/htc/evita/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
  vendor/htc/evita/proprietary/lib/libcam_oem_plugin.so:system/lib/libcam_oem_plugin.so \
  vendor/htc/evita/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
  vendor/htc/evita/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
  vendor/htc/evita/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
  vendor/htc/evita/proprietary/lib/libDxOAF.so:system/lib/libDxOAF.so \
  vendor/htc/evita/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/htc/evita/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
  vendor/htc/evita/proprietary/lib/libmmcamera_rawchipproc.so:system/lib/libmmcamera_rawchipproc.so \
  vendor/htc/evita/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
  vendor/htc/evita/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/htc/evita/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/htc/evita/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/htc/evita/proprietary/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
  vendor/htc/evita/proprietary/lib/libposteffect.so:system/lib/libposteffect.so \
  vendor/htc/evita/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
  vendor/htc/evita/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
  vendor/htc/evita/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/htc/evita/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
  vendor/htc/evita/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
  vendor/htc/evita/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
  vendor/htc/evita/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
  vendor/htc/evita/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
  vendor/htc/evita/proprietary/lib/libgps.so:system/lib/libgps.so \
  vendor/htc/evita/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
  vendor/htc/evita/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
  vendor/htc/evita/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
  vendor/htc/evita/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
  vendor/htc/evita/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
  vendor/htc/evita/proprietary/lib/libgsl.so:system/lib/libgsl.so \
  vendor/htc/evita/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/htc/evita/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
  vendor/htc/evita/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
  vendor/htc/evita/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
  vendor/htc/evita/proprietary/lib/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so \
  vendor/htc/evita/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/htc/evita/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
  vendor/htc/evita/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/htc/evita/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/htc/evita/proprietary/lib/libqdi.so:system/lib/libqdi.so \
  vendor/htc/evita/proprietary/lib/libqdp.so:system/lib/libqdp.so \
  vendor/htc/evita/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/htc/evita/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
  vendor/htc/evita/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
  vendor/htc/evita/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
  vendor/htc/evita/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
  vendor/htc/evita/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
  vendor/htc/evita/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
  vendor/htc/evita/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
  vendor/htc/evita/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
  vendor/htc/evita/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
  vendor/htc/evita/proprietary/lib/libril.so:system/lib/libril.so \
  vendor/htc/evita/proprietary/lib/hw/sensors.elite.so:system/lib/hw/sensors.elite.so \
  vendor/htc/evita/proprietary/lib/libimu.so:system/lib/libimu.so \
  vendor/htc/evita/proprietary/lib/libmllite.so:system/lib/libmllite.so \
  vendor/htc/evita/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
  vendor/htc/evita/proprietary/lib/libmpl.so:system/lib/libmpl.so \
  vendor/htc/evita/proprietary/lib/libv8.so:system/lib/libv8.so
