# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/pyramid/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/pyramid/proprietary/libcamera.so:obj/lib/libcamera.so \
    vendor/htc/pyramid/proprietary/libaudio.so:obj/lib/libaudio.so \
    vendor/htc/pyramid/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/pyramid/proprietary/libacdbloader.so:obj/lib/libacdbloader.so \
    vendor/htc/pyramid/proprietary/libacdbmapper.so:obj/lib/libacdbmapper.so \
    vendor/htc/pyramid/proprietary/libril.so:obj/lib/libril.so

# All the blobs necessary for pyramid
PRODUCT_COPY_FILES += \
    vendor/htc/pyramid/proprietary/agps_rm:/system/etc/agps_rm \
    vendor/htc/pyramid/proprietary/awb_camera:/system/bin/awb_camera \
    vendor/htc/pyramid/proprietary/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/pyramid/proprietary/btld:/system/bin/btld \
    vendor/htc/pyramid/proprietary/charging:/system/bin/charging \
    vendor/htc/pyramid/proprietary/dcvs:/system/bin/dcvs \
    vendor/htc/pyramid/proprietary/dcvsd:/system/bin/dcvsd \
    vendor/htc/pyramid/proprietary/htc_ebdlogd:/system/bin/htc_ebdlogd \
    vendor/htc/pyramid/proprietary/htcbatt:/system/bin/htcbatt \
    vendor/htc/pyramid/proprietary/hdmid:/system/bin/hdmid \
    vendor/htc/pyramid/proprietary/ipd:/system/bin/ipd \
    vendor/htc/pyramid/proprietary/ip:/system/bin/ip \
    vendor/htc/pyramid/proprietary/logcat2:/system/bin/logcat2 \
    vendor/htc/pyramid/proprietary/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/pyramid/proprietary/netmgrd:/system/bin/netmgrd \
    vendor/htc/pyramid/proprietary/netsharing:/system/bin/netsharing \
    vendor/htc/pyramid/proprietary/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/pyramid/proprietary/rild:/system/bin/rild \
    vendor/htc/pyramid/proprietary/ser2net:/system/bin/ser2net \
    vendor/htc/pyramid/proprietary/sound8x60:/system/bin/sound8x60 \
    vendor/htc/pyramid/proprietary/load-modem.sh:/system/bin/load-modem.sh \
    vendor/htc/pyramid/proprietary/mpdecision:/system/bin/mpdecision \
    vendor/htc/pyramid/proprietary/thermald:/system/bin/thermald \
    vendor/htc/pyramid/proprietary/qmuxd:/system/bin/qmuxd \
    vendor/htc/pyramid/proprietary/usbnet:/system/bin/usbnet \
    vendor/htc/pyramid/proprietary/wireless_modem:/system/xbin/wireless_modem \
    vendor/htc/pyramid/proprietary/agps_rm:/system/etc/agps_rm \
    vendor/htc/pyramid/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/pyramid/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/pyramid/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/pyramid/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/pyramid/proprietary/libOmxVdec.so:/system/lib/libOmxVdec.so \
    vendor/htc/pyramid/proprietary/libOmxCore.so:/system/lib/libOmxCore.so \
    vendor/htc/pyramid/proprietary/libOmxVenc.so:/system/lib/libOmxVenc.so \
    vendor/htc/pyramid/proprietary/libaudio.so:/system/lib/libaudio.so \
    vendor/htc/pyramid/proprietary/libaudiopolicy.so:/system/lib/libaudiopolicy.so \
    vendor/htc/pyramid/proprietary/libacdbloader.so:/system/lib/libacdbloader.so \
    vendor/htc/pyramid/proprietary/libacdbmapper.so:/system/lib/libacdbmapper.so \
    vendor/htc/pyramid/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/pyramid/proprietary/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/pyramid/proprietary/libdiag.so:/system/lib/libdiag.so \
    vendor/htc/pyramid/proprietary/libdll.so:/system/lib/libdll.so \
    vendor/htc/pyramid/proprietary/libdsutils.so:/system/lib/libdsutils.so \
    vendor/htc/pyramid/proprietary/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
    vendor/htc/pyramid/proprietary/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/pyramid/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/pyramid/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/pyramid/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/pyramid/proprietary/libidl.so:/system/lib/libidl.so \
    vendor/htc/pyramid/proprietary/libril.so:/system/lib/libril.so \
    vendor/htc/pyramid/proprietary/libhtc_ril_switch.so:/system/lib/libhtc_ril_switch.so \
    vendor/htc/pyramid/proprietary/liboverlay.so:/system/lib/liboverlay.so \
    vendor/htc/pyramid/proprietary/libganril.so:/system/lib/libganril.so \
    vendor/htc/pyramid/proprietary/libkineto.so:/system/lib/libkineto.so \
    vendor/htc/pyramid/proprietary/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/pyramid/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/pyramid/proprietary/libmpl.so:/system/lib/libmpl.so \
    vendor/htc/pyramid/proprietary/libmpl_jni.so:/system/lib/libmpl_jni.so \
    vendor/htc/pyramid/proprietary/libmllite.so:/system/lib/libmllite.so \
    vendor/htc/pyramid/proprietary/libmlplatform.so:/system/lib/libmlplatform.so \
    vendor/htc/pyramid/proprietary/libnetmgr.so:/system/lib/libnetmgr.so \
    vendor/htc/pyramid/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/pyramid/proprietary/libqdp.so:/system/lib/libqdp.so \
    vendor/htc/pyramid/proprietary/libqmi.so:/system/lib/libqmi.so \
    vendor/htc/pyramid/proprietary/libqmiservices.so:/system/lib/libqmiservices.so \
    vendor/htc/pyramid/proprietary/vpimg:/system/etc/vpimg \
    vendor/htc/pyramid/proprietary/gralloc.msm8660.so:/system/lib/hw/gralloc.msm8660.so \
    vendor/htc/pyramid/proprietary/copybit.msm8660.so:/system/lib/hw/copybit.msm8660.so \
    vendor/htc/pyramid/proprietary/gps.pyramid.so:/system/lib/hw/gps.pyramid.so \
    vendor/htc/pyramid/proprietary/gralloc.default.so:/system/lib/hw/gralloc.default.so \
    vendor/htc/pyramid/proprietary/lights.msm8660.so:/system/lib/hw/lights.msm8660.so \
    vendor/htc/pyramid/proprietary/overlay.default.so:/system/lib/hw/overlay.default.so \
    vendor/htc/pyramid/proprietary/sensors.pyramid.so:/system/lib/hw/sensors.pyramid.so
