# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/shooter/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/shooter/proprietary/camera.default.so:obj/lib/hw/camera.default.so \
    vendor/htc/shooter/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/shooter/proprietary/libacdbloader.so:obj/lib/libacdbloader.so \
    vendor/htc/shooter/proprietary/libacdbmapper.so:obj/lib/libacdbmapper.so \
    vendor/htc/shooter/proprietary/libv8.so:obj/lib/libv8.so

# All the blobs necessary for shooter
PRODUCT_COPY_FILES += \
    vendor/htc/shooter/proprietary/charging:system/bin/charging \
    vendor/htc/shooter/proprietary/hdmid:system/bin/hdmid \
    vendor/htc/shooter/proprietary/htc_ebdlogd:system/bin/htc_ebdlogd \
    vendor/htc/shooter/proprietary/htcbatt:system/bin/htcbatt \
    vendor/htc/shooter/proprietary/load-modem.sh:system/bin/load-modem.sh \
    vendor/htc/shooter/proprietary/logcat2:system/bin/logcat2 \
    vendor/htc/shooter/proprietary/mpdecision:system/bin/mpdecision \
    vendor/htc/shooter/proprietary/netmgrd:system/bin/netmgrd \
    vendor/htc/shooter/proprietary/qmuxd:system/bin/qmuxd \
    vendor/htc/shooter/proprietary/rmt_storage:system/bin/rmt_storage \
    vendor/htc/shooter/proprietary/snd3254:system/bin/snd3254 \
    vendor/htc/shooter/proprietary/thermald:system/bin/thermald \
    vendor/htc/shooter/proprietary/wireless_modem:system/bin/wireless_modem \
    vendor/htc/shooter/proprietary/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/htc/shooter/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/htc/shooter/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/shooter/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/shooter/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/shooter/proprietary/libgsl.so:system/lib/libgsl.so \
    vendor/htc/shooter/proprietary/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/htc/shooter/proprietary/libC2D2.so:system/lib/libC2D2.so \
    vendor/htc/shooter/proprietary/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/htc/shooter/proprietary/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    vendor/htc/shooter/proprietary/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    vendor/htc/shooter/proprietary/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/htc/shooter/proprietary/libaudcal.so:system/lib/libaudcal.so \
    vendor/htc/shooter/proprietary/libaudcalwb.so:system/lib/libaudcalwb.so \
    vendor/htc/shooter/proprietary/libaudcal_nel.so:system/lib/libaudcal_nel.so \
    vendor/htc/shooter/proprietary/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/htc/shooter/proprietary/libacdbmapper.so:system/lib/libacdbmapper.so \
    vendor/htc/shooter/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/htc/shooter/proprietary/libdll.so:system/lib/libdll.so \
    vendor/htc/shooter/proprietary/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/htc/shooter/proprietary/libdsutils.so:system/lib/libdsutils.so \
    vendor/htc/shooter/proprietary/libidl.so:system/lib/libidl.so \
    vendor/htc/shooter/proprietary/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/htc/shooter/proprietary/libqdp.so:system/lib/libqdp.so \
    vendor/htc/shooter/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/htc/shooter/proprietary/libhtc_ril.so:system/lib/libhtc_ril.so \
    vendor/htc/shooter/proprietary/libcamerapp.so:system/lib/libcamerapp.so \
    vendor/htc/shooter/proprietary/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/htc/shooter/proprietary/libcameraface.so:system/lib/libcameraface.so \
    vendor/htc/shooter/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/htc/shooter/proprietary/libOlaEngine.so:system/lib/libOlaEngine.so \
    vendor/htc/shooter/proprietary/libposteffect.so:system/lib/libposteffect.so \
    vendor/htc/shooter/proprietary/libgemini.so:system/lib/libgemini.so \
    vendor/htc/shooter/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/htc/shooter/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/htc/shooter/proprietary/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/htc/shooter/proprietary/libv8.so:system/lib/libv8.so \
    vendor/htc/shooter/proprietary/camera.default.so:system/lib/hw/camera.default.so \
    vendor/htc/shooter/proprietary/lights.msm8660.so:system/lib/hw/lights.msm8660.so \
    vendor/htc/shooter/proprietary/libmpl.so:system/lib/libmpl.so \
    vendor/htc/shooter/proprietary/libmllite.so:system/lib/libmllite.so \
    vendor/htc/shooter/proprietary/libmlplatform.so:system/lib/libmlplatform.so \
    vendor/htc/shooter/proprietary/sensors.shooter.so:system/lib/hw/sensors.shooter.so
