# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/lexikon/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/lexikon/proprietary/libcamera.so:obj/lib/libcamera.so \
    vendor/htc/lexikon/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so

# All the blobs necessary for lexikon
PRODUCT_COPY_FILES += \
    vendor/htc/lexikon/proprietary//akmd:/system/bin/akmd \
    vendor/htc/lexikon/proprietary/awb_camera:/system/bin/awb_camera \
    vendor/htc/lexikon/proprietary/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/lexikon/proprietary/dmagent:/system/bin/dmagent \
    vendor/htc/lexikon/proprietary/htc_ebdlogd:/system/bin/htc_ebdlogd \
    vendor/htc/lexikon/proprietary/logcat2:/system/bin/logcat2 \
    vendor/htc/lexikon/proprietary/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/lexikon/proprietary/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/lexikon/proprietary/record:/system/bin/record \
    vendor/htc/lexikon/proprietary/recordvideo:/system/bin/recordvideo \
    vendor/htc/lexikon/proprietary/AudioBTID.csv:/system/etc/AudioBTID.csv \
    vendor/htc/lexikon/proprietary/AdieHWCodec.csv:/system/etc/AdieHWCodec.csv \
    vendor/htc/lexikon/proprietary/AdieHWCodec_NEL.csv:/system/etc/AdieHWCodec_NEL.csv \
    vendor/htc/lexikon/proprietary/TPA2051_CFG.csv:/system/etc/TPA2051_CFG.csv \
    vendor/htc/lexikon/proprietary/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/htc/lexikon/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/lexikon/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/lexikon/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/lexikon/proprietary/libGLESv2S3D_adreno200.so:/system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/htc/lexikon/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/lexikon/proprietary/libsc-a2xx.so:/system/lib/libsc-a2xx.so \
    vendor/htc/lexikon/proprietary/libc2d2_z180.so:/system/lib/libc2d2_z180.so \
    vendor/htc/lexikon/proprietary/libC2D2.so:/system/lib/libC2D2.so \
    vendor/htc/lexikon/proprietary/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/htc/lexikon/proprietary/libOpenMAXAL.so:/system/lib/libOpenMAXAL.so \
    vendor/htc/lexikon/proprietary/libOpenSLES.so:/system/lib/libOpenSLES.so \
    vendor/htc/lexikon/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/lexikon/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/lexikon/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/lexikon/proprietary/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/lexikon/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/lexikon/proprietary/libwvm.so:/system/lib/libwvm.so \
    vendor/htc/lexikon/proprietary/libwvdrm_L3.so:/system/lib/libwvdrm_L3.so \
    vendor/htc/lexikon/proprietary/libWVStreamControlAPI_L3.so:/system/lib/libWVStreamControlAPI_L3.so \
    vendor/htc/lexikon/proprietary/libposteffect.so:/system/lib/libposteffect.so \
    vendor/htc/lexikon/proprietary/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/lexikon/proprietary/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/lexikon/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/lexikon/proprietary/libims_ril.so:/system/lib/libims_ril.so \
    vendor/htc/lexikon/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so
