# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/glacier/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
  vendor/htc/glacier/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

PRODUCT_COPY_FILES += \
  vendor/htc/glacier/proprietary/etc/vpimg:system/etc/vpimg \
  vendor/htc/glacier/proprietary/bin/akmd:system/bin/akmd \
  vendor/htc/glacier/proprietary/bin/awb_camera:system/bin/awb_camera \
  vendor/htc/glacier/proprietary/bin/bma150_usr:system/bin/bma150_usr \
  vendor/htc/glacier/proprietary/bin/lsc_camera:system/bin/lsc_camera \
  vendor/htc/glacier/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/htc/glacier/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
  vendor/htc/glacier/proprietary/lib/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
  vendor/htc/glacier/proprietary/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
  vendor/htc/glacier/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
  vendor/htc/glacier/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
  vendor/htc/glacier/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/htc/glacier/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/htc/glacier/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/htc/glacier/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/htc/glacier/proprietary/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
  vendor/htc/glacier/proprietary/lib/libposteffect.so:system/lib/libposteffect.so \
  vendor/htc/glacier/proprietary/lib/libchromatix_s5k4e1gx_default_video.so:system/lib/libchromatix_s5k4e1gx_default_video.so \
  vendor/htc/glacier/proprietary/lib/libchromatix_s5k4e1gx_preview.so:system/lib/libchromatix_s5k4e1gx_preview.so \
  vendor/htc/glacier/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
  vendor/htc/glacier/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so \
  vendor/htc/glacier/proprietary/lib/libwvm.so:system/lib/libwvm.so \
  vendor/htc/glacier/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
  vendor/htc/glacier/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
  vendor/htc/glacier/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
  vendor/htc/glacier/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/htc/glacier/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
  vendor/htc/glacier/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
  vendor/htc/glacier/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
  vendor/htc/glacier/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
  vendor/htc/glacier/proprietary/lib/libgsl.so:system/lib/libgsl.so \
  vendor/htc/glacier/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
  vendor/htc/glacier/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
  vendor/htc/glacier/proprietary/lib/libhtc_ril.so:system/lib/libhtc_ril.so
