# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/glacier/setup-makefiles.sh

PRODUCT_COPY_FILES += \
  vendor/htc/glacier/proprietary/bin/akmd:system/bin/akmd \
  vendor/htc/glacier/proprietary/bin/awb_camera:system/bin/awb_camera \
  vendor/htc/glacier/proprietary/bin/lsc_camera:system/bin/lsc_camera \
  vendor/htc/glacier/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/htc/glacier/proprietary/lib/libchromatix_s5k4e1gx_default_video.so:system/lib/libchromatix_s5k4e1gx_default_video.so \
  vendor/htc/glacier/proprietary/lib/libchromatix_s5k4e1gx_preview.so:system/lib/libchromatix_s5k4e1gx_preview.so \
  vendor/htc/glacier/proprietary/lib/libhtc_ril.so:system/lib/libhtc_ril.so
